### ISSUE TITLE
Linking molfams

### ISSUE THREAD

**Issue by louwenjjr** [NPLinker/nplinker#54]
Hi again Andrew!
I was wondering if it is already possible to link MFs to GCFs, as currently it is only the spectra that are linked. When quickly looking at the linking code I see this bit in methods.py:

```
# TODO molfam support still missing here (as in data_linking.py)

            # results is a (3, x) array for spec/molfam input, where (1, :) gives src obj ID, (2, :) gives
            # dst obj ID, and (3, :) gives scores
            # for GCFs you get [spec, molfam] with above substructure

            # NOTE: need to use sets here because if the "else" cases are executed 
            # can get lots of duplicate object IDs which messes everything up
```

Does that mean that it is indeed not possible yet? Is there a workaround? And if not, I could also spend some time implementing this, maybe you could give me a nudge in the right direction on how to get started with this. :)

Thanks!

**Comment by andrewramsay** [comment]
I think it should be possible, at least for Metcalf scoring. The code in data_linking.py does seem to set up all the data structures required for using MFs, but Florian Huber wrote most of it and I'm not 100% sure what my TODO comment in methods.py actually means looking at it now, it was added quite a while ago. It might be outdated or there might be some other problem I'm forgetting that led me to skip over it originally. I'll need to test it and see if anything breaks! 

If you can leave this with me until next week (I'm on annual leave until Monday) then I can have a proper look at it. I don't think there would be too much to change in methods.py itself, but making the new linking mode available in the webapp would require a larger ripple of changes through that section of the code. 

e.g. if I remember correctly the module that generates the data structures which manage all the links between objects in the tables is written with the assumption that linking only exists between "adjacent" pairs of object types: MF<=>Spectrum, Spectrum<=>BGC, BGC<=>GCF. So if we now want to add MF<=>GCF that might mean quite a lot has to be changed to accommodate this within the module itself, and then there will be further changes in how the webapp uses the module. But it should be doable.

**Comment by louwenjjr** [comment]
Hey thanks for the quick reply :)

> If you can leave this with me until next week (I'm on annual leave until Monday) then I can have a proper look at it.

Yes most definitely! It is definitely not urgent, but would be nice to play around with this a bit as well, as I see some links that would benefit from linking the whole MF to GCF instead of just the spectra.

> MF<=>Spectrum, Spectrum<=>BGC, BGC<=>GCF. So if we now want to add MF<=>GCF

Hmm, but now GCF <=> Spectrum is already implemented right?

> changes in how the webapp uses the module

I am now using the python code itself, as I want to add some code as well, so changes to the webapp are of less importance to me now.

**Comment by justinjjvanderhooft** [comment]
MF<=>Spectrum, Spectrum<=>BGC, BGC<=>GCF. So if we now want to add MF<=>GCF
Hmm, but now GCF <=> Spectrum is already implemented right?
--> Yes, but the MF adds another layer of complexity here.

changes in how the webapp uses the module
I am now using the python code itself, as I want to add some code as well, so changes to the webapp are of less importance to me now.
--> sure, but it would be good to keep in mind that it should be compatible with the web app!

thanks @andrewramsay and enjoy your break!! :-)

**Comment by andrewramsay** [comment]
> Hmm, but now GCF <=> Spectrum is already implemented right?

If you're using the API directly yes you can already pass in GCFs to the scoring methods and get Spectra back, but the tables code that the webapp uses for filtering objects is a bit different - if you look [here](https://github.com/sdrogers/nplinker/blob/e7b79c19771dee4f4a4353309ccab1dcb7b4a55d/webapp/npapp/tables_functions.py#L97) you can see some properties of the 7 database tables it ultimately creates. 4 of them directly correspond to the visible tables in the webapp, and then there are 3 further tables (mf_spectra, spec_bgc, bgc_gcf) which contain the links between each of those 3 pairs I mentioned. But perhaps we wouldn't even need to update this as much as I thought since the tables are only supposed to be for making selections of objects to run scoring on anyway, hadn't thought that all the way through. 

> I am now using the python code itself, as I want to add some code as well, so changes to the webapp are of less importance to me now.

Oh I see, that's good to know! As far as I'm aware most of the other users so far have been using the webapp so it'll be great to have someone using the Python API. If we can make the changes at that level as a first step it makes things a lot easier and it shouldn't be too hard to avoid breaking the webapp. Once we're happy with it I can update that separately. 

Anyway I'll get back to this on Monday, but I do have a quick question about the implementation details. What is the difference between running Metcalf scoring on a MolFam vs on a list of all spectra in that MolFam? When you run the scoring on spectra each one receives its own Metcalf score (same for GCFs), so is there some kind of cumulative scoring that should be performed across the spectra in each MF in order to give an overall result for each one? If you use multiple MFs as input to scoring you'd want to be able to rank them somehow afterwards right?

**Comment by louwenjjr** [comment]
> Oh I see, that's good to know! As far as I'm aware most of the other users so far have been using the webapp so it'll be great to have someone using the Python API. If we can make the changes at that level as a first step it makes things a lot easier and it shouldn't be too hard to avoid breaking the webapp. Once we're happy with it I can update that separately.

Sounds good! Maybe also good to say what I am trying to do: We are trying to add an extra filtering step for the link results, where we filter out links based on non-matching bgc-class vs chemical-class. So let's say if a bgc is a terpene and a spectrum is peptide related than we consider this unlikely and filter it out/rank it down.

> Anyway I'll get back to this on Monday, but I do have a quick question about the implementation details. What is the difference between running Metcalf scoring on a MolFam vs on a list of all spectra in that MolFam? When you run the scoring on spectra each one receives its own Metcalf score (same for GCFs), so is there some kind of cumulative scoring that should be performed across the spectra in each MF in order to give an overall result for each one? If you use multiple MFs as input to scoring you'd want to be able to rank them somehow afterwards right?

We were still discussing this a bit, but my idea is to just combine all strain occurrences from the spectra of a molfam to the strain occurrence of the molfam. This would especially help with compounds that produce slightly different spectra that are not grouped together in the cluster indices that well, so grouping them in Molfams would work better. Of course feel free to share your thoughts on this as well!

And indeed enjoy your break! :)

**Comment by andrewramsay** [comment]
Just been looking at this a bit and I think there is definitely some work needing done in data_linking.py to make this scoring mode work properly. 

Since the webapp hasn't had MF scoring as an option it hasn't been tested much, and I can see there are a couple of places where I've tweaked the original code to work better with NPLinker when it has Spectra/GCF input but not yet with MolFams. 

Another issue is that data_linking.py has this parameter called include_singletons used when collecting the MF-GCF links that defaults to False:

https://github.com/sdrogers/nplinker/blob/e7b79c19771dee4f4a4353309ccab1dcb7b4a55d/prototype/nplinker/scoring/data_linking.py#L104

Does it make sense to include singleton MFs or should this be left as-is? I'm not sure there's anywhere else where we currently do much to distinguish between singleton and non-singleton MFs other than indicating them in the webapp. 

If we don't want to include them this will probably mean some further changes are required as data_linking.py uses the internal IDs NPLinker assigns to each set of objects. If the singletons aren't included in the set of MFs the numbering may not be consecutive any more, and that will break things. Or are singleton MFs mostly useless to keep around anyway? I could filter them out earlier in the loading process if needed. 

Out of interest do you have an example (maybe from a platform dataset) where you already know there are links between some MFs and GCFs? It would be a good way to check if any updates I make are working.

**Comment by justinjjvanderhooft** [comment]
@andrewramsay thanks! I would also load in the singletons as they are part of the analysis, in fact they are MFs of size 1 ;-) - if that doesn't take too much effort of course.... 
Also, there are examples in the Paired Omics Data Platform of gene cluster to MF links, i.e. the famous Crusemann project contains quite a few of them: https://pairedomicsdata.bioinformatics.nl/projects/297c364c-b154-4edd-a7d5-68decf9effa2.4
I hope that this is helpful! 😎

**Comment by justinjjvanderhooft** [comment]
I see. Well, if you could have a look what is causing that error and if that is not too deep down in the code, then you can decide whether filtering them out a priori is the better option....

**Comment by andrewramsay** [comment]
Turns out some of the problems were being caused by the way we grafted on standardised Metcalf scoring over the original implementation. That's the part that the "TODO molfam support" comment was in reference to, I must have decided to skip it in favour of getting the Spectra/GCF modes working as quickly as possible. 

You can see the line here: https://github.com/sdrogers/nplinker/blob/bfe558a6f1bacc3300a0fad87f0fffa3c78f7855/prototype/nplinker/scoring/methods.py#L495 which checks if standardised scoring is being used, and if not it skips that whole block where the TODO comment is. 

I've made a couple of small changes to data_linking.py and have set it to include singletons by default now instead of ignoring them as far as Metcalf scoring is concerned: https://github.com/sdrogers/nplinker/blob/f7bb7d0539e67d775376391871184109a0f7058a/prototype/nplinker/scoring/methods.py#L468

If you pull the latest version of the code, you should then be able to get MolFam-GCF links by configuring the Metcalf scoring object like this:
```python
npl = NPLinker(...)
npl.load_data()
mc = npl.scoring_method('metcalf')
mc.standardised = False
link_data = npl.get_links(npl.molfams[:10], mc)
```

From the quick testing I've done that seems to be working, so it might be a good short-term solution to allow you to do stuff with these links. 

As for updating the standardised scoring, I'm not sure exactly how to do this. Normally when it has a Spectrum + a GCF, it can take the number of strains from each one and use that to look up the Metcalf score for that combination of values. https://github.com/sdrogers/nplinker/blob/f7bb7d0539e67d775376391871184109a0f7058a/prototype/nplinker/scoring/methods.py#L539

But if it has a MolFam + a GCF, should it count all the (unique) strains from each of the Spectra in the MolFam and use that as the value? Or does it need to be handled in a more complex way?

**Comment by justinjjvanderhooft** [comment]
Good point @andrewramsay - here @grimur may also want to chip in. I think this would deserve some proper research and could well be part of a MSc project or follow-up work within the grant that was submitted or other projects. Until then, I would suggest to count all the (unique) strains from each of the MolFam spectra and use that value (as you suggest).

**Comment by andrewramsay** [comment]
@louwenjjr I've just made some changes in c0ece3073bb5283e2aaffcbe2afaedecbd2688ce that you might want to try out. I'm not sure why I had done things the way I had originally but it seemed a bit overcomplicated even though it wasn't properly handling MolFams. 

The new version should be more efficient and work the same way as data_linking.py does: give it Spectra or MolFam input and you get Spectrum<=>GCF or MolFam<=>GCF links respectively, give it GCF input and you will get some mix of GCF<=>Spectrum *and* GCF<=>MolFam links. Those should be easy to distinguish in the results using the type of the `.target` attribute for each ObjectLink.

**Comment by louwenjjr** [comment]
Sounds very good Andrew, I'll give it a try!
